services:
  # Service Frontend Angular
  - type: web
    name: audacieuses-web
    env: node
    buildCommand: |
      cd AudacieusesWeb
      npm install
      npm run build
    startCommand: |
      cd AudacieusesWeb
      npm install -g serve
      serve -s dist/audacieuses-web/browser -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NPM_VERSION
        value: 10.2.4
    healthCheckPath: /
    autoDeploy: true
    plan: free

  # Service API PHP
  - type: web
    name: audacieuses-api
    env: php
    buildCommand: |
      composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT public/index.php
    envVars:
      - key: PHP_VERSION
        value: 8.2.0
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASS
        value: ${DB_PASS}
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 