services:
  # Front-end Angular
  - type: web
    name: audacieuses-web
    env: node
    region: frankfurt
    buildCommand: |
      cd AudacieusesWeb
      npm install
      npm run build
    startCommand: |
      cd AudacieusesWeb
      npm install -g serve
      serve -s dist/audacieuses-web/browser -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NPM_VERSION
        value: 10.2.4
    healthCheckPath: /
    autoDeploy: true
    plan: free

  # Back-end Node.js API
  - type: web
    name: audacieuses-api
    env: node
    region: frankfurt
    buildCommand: |
      cd AudacieusesAPI
      npm install
    startCommand: |
      cd AudacieusesAPI
      npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: audacieuses-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: audacieuses-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: audacieuses-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: audacieuses-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://audacieuses-web.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free

# Base de données PostgreSQL
databases:
  - name: audacieuses-db
    region: frankfurt
    plan: free
    type: postgres
    version: "15"