services:
  # Service Frontend Angular
  - type: web
    name: audacieuses-web
    env: node
    buildCommand: |
      cd AudacieusesWeb
      npm install
      npm run build
    startCommand: |
      cd AudacieusesWeb
      npm install -g serve
      serve -s dist/audacieuses-web/browser -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NPM_VERSION
        value: 10.2.4
    healthCheckPath: /
    autoDeploy: true
    plan: free

  # Service API Node.js
  - type: web
    name: audacieuses-api
    env: node
    buildCommand: |
      cd AudacieusesAPI
      npm install
    startCommand: |
      cd AudacieusesAPI
      npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: audacieuses-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: audacieuses-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: audacieuses-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: audacieuses-db
          property: password
      - key: FRONTEND_URL
        value: https://audacieuses-web.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free

  # Base de données MySQL
databases:
  - name: audacieuses-db
    plan: free
    type: mysql
        value: 8.2.0
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASS
        value: ${DB_PASS}
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 